### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by neoncitylights** [neoncitylights/sdmx#18]
- [ ] Write Top-level documentation to symbols
- [ ] Expand top-level documentation for modules
- [ ] Examples in README.md and docs
- [ ] Write JSON deserialization integration tests that pass
- [ ] Write JSON serialization integration tests that pass
- [ ] more?
