### ISSUE TITLE
Roadmap to v1 for sdmx_csv

### ISSUE THREAD

**Issue by neoncitylights** [neoncitylights/sdmx#30]
- [x] Write top-level documentation for symbols
 - [ ] Implement conditional deserialization
 - [ ] Implement serialization
 - [ ] Write CSV deserialization tests
 - [ ] Write CSV serialization tests
 - [ ] Examples in README.md and docs
